service: returns-test-mentory
frameworkVersion: '2'
useDotenv: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  region: us-west-2
  runtime: nodejs14.x
  stage: ${opt:stage,'dev'}
  httpApi:
    cors: true
  timeout: 30
  memorySize: 128
  lambdaHashingVersion: '20201221'

functions:
  returnsReadEmails:
    handler: src/handler.get
    name: 'returns-test-get-${self:provider.stage}'
    description: 'Return Project Test GET'
    environment:
      NAME_PROJECT: ${env:NAME_PROJECT}
    events:
      - httpApi:
          path: /products/{id}
          method: get
  returnsFunctionsTwo:
    handler: src/handler.save
    name: 'returns-test-post-${self:provider.stage}'
    description: 'Return Project Test POST'
    environment:
      NAME_PROJECT: ${env:NAME_PROJECT}
    events:
      - httpApi:
          path: /products
          method: post
